# Generated by Django 3.0.5 on 2020-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_auto_20200406_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='en-us', max_length=35),
        ),
    ]
